### ISSUE TITLE
Copyright notice

### ISSUE THREAD

**Issue by EJP286CRSKW** [javadev/calculator#18]
The copyright notice states "Copyright 2013-2023 Valentyn Kolesnikov".

This code was published by Ronald Mak in his book Java Number Cruncher: the Java Programmer's Guide to Numerical Computing, Prentice Hall 2002. The copyright therefore belongs to him.

The licence grant is therefore also invalid.

**Comment by javadev** [comment]
I authored this code, and it is not sourced from any other repositories.
